language: node_js
node_js:
  - 'stable'
  - '5.1.0'
before_script:
  - npm install bower
  - bower install
  - npm install tsd
  - tsd install
  - gem update --system
  - gem install sass
  - npm install grunt-cli
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/01a13e1e4162d08aebee
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: always    # options: [always|never|change] default: always
env:
  global:
    # https://github.com/DefinitelyTyped/tsd#tsdrc
    # Token has no scope (read-only access to public information)
    - TSD_GITHUB_TOKEN=3a9ce4a942d02979bb3825a327da048f3efd8afd