language: node_js

node_js:
  - '5.1.0'

env:
  global:
    # https://github.com/DefinitelyTyped/tsd#tsdrc
    # Token has no scope (read-only access to public information)
    - TSD_GITHUB_TOKEN=3a9ce4a942d02979bb3825a327da048f3efd8afd

notifications:
  slack:
    rooms:
      - koluki:VDaXhjBB9j25YIuN7jZDWoxd#general
    on_success: always
    on_failure: always
    on_start: always
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/01a13e1e4162d08aebee
      - https://api.loader.io/v2/tests/b5f7d60147179918f406d86d19fb238b/token/43a0a27747c02ff7b39026b771753397/run
    on_success: always
    on_failure: never
    on_start: never

install:
  - npm install bower
  - bower install
  - npm install tsd
  - tsd install
  - gem update --system
  - gem install sass
  - npm install -g grunt-cli
  - npm install
  - ./node_modules/protractor/bin/webdriver-manager update

before_script:
  - export DISPLAY=:99.0
  - /sbin/start-stop-daemon --start --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16
  - sleep 3
  - nohup bash -c "./node_modules/protractor/bin/webdriver-manager start 2>&1 &"
  - sleep 3

script:
  - grunt test