language: node_js

node_js:
  - 'stable'
  - '5.1.0'

env:
  global:
    # https://github.com/DefinitelyTyped/tsd#tsdrc
    # Token has no scope (read-only access to public information)
    - TSD_GITHUB_TOKEN=3a9ce4a942d02979bb3825a327da048f3efd8afd

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/01a13e1e4162d08aebee
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: always    # options: [always|never|change] default: always

install:
  - npm install bower
  - bower install
  - npm install tsd
  - tsd install
  - gem update --system
  - gem install sass
  - npm install -g grunt-cli
  - npm install
  - ./node_modules/protractor/bin/webdriver-manager update

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - nohup bash -c "./node_modules/protractor/bin/webdriver-manager start 2>&1 &"
  - sleep 3

script:
  - grunt test